### Importing Essential Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

### Load data

In [2]:
df=pd.read_csv('ex1data2.txt',names=['size(in sq. feet)','no. of bedrooms','price'])

In [3]:
df.describe()

size(in sq. feet)  no. of bedrooms          price
count          47.000000        47.000000      47.000000
mean         2000.680851         3.170213  340412.659574
std           794.702354         0.760982  125039.899586
min           852.000000         1.000000  169900.000000
25%          1432.000000         3.000000  249900.000000
50%          1888.000000         3.000000  299900.000000
75%          2269.000000         4.000000  384450.000000
max          4478.000000         5.000000  699900.000000

### Feature scaling

In [4]:
df = ( df - df.mean() ) / df.std()  # mean normalization using standard deviation

In [5]:
df.describe()

size(in sq. feet)  no. of bedrooms         price
count       4.700000e+01     4.700000e+01  4.700000e+01
mean        1.889741e-17     2.279500e-16 -8.031401e-17
std         1.000000e+00     1.000000e+00  1.000000e+00
min        -1.445423e+00    -2.851859e+00 -1.363666e+00
25%        -7.155897e-01    -2.236752e-01 -7.238702e-01
50%        -1.417900e-01    -2.236752e-01 -3.239979e-01
75%         3.376348e-01     1.090417e+00  3.521863e-01
max         3.117292e+00     2.404508e+00  2.874981e+00

In [6]:
X=np.array(df['size(in sq. feet)'],df['no. of bedrooms']).reshape(-1,1)

In [7]:
y=np.array(df['price']).reshape(-1,1)

### Train test split

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y)

In [9]:
X_train

array([[-1.44542274e+00],
       [-4.86733818e-02],
       [-5.87239800e-01],
       [ 1.65243186e-01],
       [-8.56523009e-01],
       [-1.25918949e+00],
       [-7.21881404e-01],
       [-1.97317285e-02],
       [-1.87089985e-01],
       [-1.00374794e+00],
       [ 4.94765729e-02],
       [ 1.30009869e-01],
       [-4.23656542e-01],
       [-2.94048269e-01],
       [ 3.76643089e-01],
       [-1.39273340e-01],
       [ 6.61026291e-01],
       [ 2.78635031e+00],
       [-5.04189838e-01],
       [ 7.12617934e-01],
       [ 1.25747602e+00],
       [ 3.11729182e+00],
       [-8.56737193e-04],
       [ 8.00701226e-01],
       [-9.21956312e-01],
       [-1.13335621e+00],
       [-7.09298077e-01],
       [-7.35723065e-01],
       [-7.81023044e-01],
       [ 2.50809813e-01],
       [-1.00752294e+00],
       [-4.99156507e-01],
       [ 7.65467909e-01],
       [ 1.29648433e+00],
       [-9.62222960e-01]])

In [10]:
X_test

array([[ 1.4298676 ],
       [-0.14179001],
       [ 0.29862646],
       [ 0.50247636],
       [ 2.37739217],
       [ 0.20299317],
       [-0.63757311],
       [-0.95844796],
       [-0.68287309],
       [-0.0763567 ],
       [-0.23868163],
       [-0.20344831]])

In [11]:
y_test

array([[ 1.91528737],
       [-0.68308324],
       [-0.08407444],
       [ 0.22862575],
       [ 1.86730269],
       [-0.42716493],
       [-0.78305133],
       [-0.88381916],
       [ 0.99238196],
       [-0.80305294],
       [-0.43596212],
       [ 0.0758745 ]])

## Training the model
### Multivariate Linear Regression

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
reg=LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [14]:
y_pred=reg.predict(X_test)

In [15]:
y_pred

array([[ 1.26020776],
       [-0.1046601 ],
       [ 0.27780888],
       [ 0.45483737],
       [ 2.08306245],
       [ 0.19475847],
       [-0.53521089],
       [-0.81386686],
       [-0.57455056],
       [-0.04783614],
       [-0.18880328],
       [-0.15820576]])

### Evaluation of the model

In [16]:
from sklearn.metrics import mean_absolute_error

In [17]:
mean_absolute_error(y_test, y_pred)

0.4817051675583292

In [18]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.5831316763299483